### ISSUE TITLE
F1 network is not same as orignal paper

### ISSUE THREAD

**Issue by ghost** [luoyetx/deep-landmark#10]
thanks for your sharing code and I have a question to ask you
1.the F1 network is not same as orignal paper,did you modify it?
2.in paper in the F1 network the first conv is CR(4,20,2,2), and 2 means weight sharing parameters, each map in conv evenly divided into 2 by 2 region ,and I don't know in F1 network where reflect 2 by 2 region?

**Comment by luoyetx** [comment]
Since Caffe doesn't support Local Convolution Layer, Yes, I modify the network structure and use the traditional Convolution Layer.

**Comment by liz6688** [comment]
@luoyetx cafffe doesn't support local convolution layer, which deep learning toolbox support?

**Comment by luoyetx** [comment]
@liz6688 I'm using no local convolution layer. Just traditional convolution layer and some modifications to the network structure.

**Comment by liz6688** [comment]
@luoyetx I'm trying to implement the F1 network as orignal paper, do you know which deep learning toolbox support local convolution layer?

**Comment by luoyetx** [comment]
@liz6688 It seems torch support local convolution layer, look docs [here](https://github.com/torch/nn/blob/master/doc/convolution.md#nn.SpatialConvolutionLocal), but it's Lua, and seems [pytorch](https://github.com/pytorch/pytorch) current don't have this feature, track this [issue](https://github.com/pytorch/pytorch/issues/499). Actually, Caffe does have unofficial implement of Local Conv, view this [issue](https://github.com/BVLC/caffe/pull/1271) for more information.

**Comment by liz6688** [comment]
@luoyetx THX
