### ISSUE TITLE
A question about face detection in README

### ISSUE THREAD

**Issue by xvbw** [luoyetx/deep-landmark#13]
I'm curious about the face detector.
In the README file as shown below, there are several red boxes that indicate the detected faces, however, I could not figure out what algorithm is used to detect these. Did you just manually selected bounding boxes? or used the author's face detector(http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm#ref)? I cannot find any information about author's face detector and wonder if you used your own face detector or directly used author's face detector.
Or if you know anything about the author's face detector, would you please let me know where I can find related paper or information?
Thanks.

![screenshot from 2016-05-12 22 37 37](https://cloud.githubusercontent.com/assets/12380953/15216482/32b209ac-1892-11e6-921b-88fe560172e9.png)

**Comment by luoyetx** [comment]
@xvbw you can find the detection code [here](https://github.com/luoyetx/deep-landmark/blob/master/webapp%2Flandmark.py#L183-L196) and I also modify the bounding box to fit the training data bbox [here](https://github.com/luoyetx/deep-landmark/blob/master/webapp%2Flandmark.py#L218). It's just a VJ detector from OpenCV with refined bbox.

**Comment by xvbw** [comment]
Thanks!
