### ISSUE TITLE
pre-trained models?

### ISSUE THREAD

**Issue by iqbalnaved** [luoyetx/deep-landmark#20]
I coudn't find any pretrained models under the model folder. Can you make them available for landmark detection ? Because the original authors only provide windows version, a linux implementation will be very much appreciated.

Thanks!

**Comment by luoyetx** [comment]
The pre-trained models are under [webapp/v0.0.6](https://github.com/luoyetx/deep-landmark/tree/master/webapp/v0.0.6).
