### ISSUE TITLE
why use the flatten layer and concat layer in level 1?

### ISSUE THREAD

**Issue by Dan1900** [luoyetx/deep-landmark#23]
Firstly,thank you for sharing your code. I run it and got good performance,but I found it not follow the paper strictly.I found in level 1, you use the flatten layer and concat layer,why? would you please tell me the reason or give me some reference source.I am a totally newer in this field, thank you very much.

**Comment by luoyetx** [comment]
@Dan1900 the original paper use local convolution layer in level 1 which is not supported by Caffe. I borrow some idea from DeepID network, the paper is [here](http://mmlab.ie.cuhk.edu.hk/pdf/YiSun_CVPR14.pdf). The network connects last convolution layer and pooling layer to construct a feature (fully connected layer), I use this structure to make the network more complex.

**Comment by Dan1900** [comment]
@luoyetx ,thank you very much!
