### ISSUE TITLE
sh: 1: caffe: not found

### ISSUE THREAD

**Issue by NIEYALI** [luoyetx/deep-landmark#26]
I met one problem, when I run 
"python2.7 prototxt/generate.py CPU

# level-1
python2.7 dataset/level1.py
rm -rf log/train1.log
echo "Train LEVEL-1"
python2.7 train/level.py 1 pool_on 

echo "=.=""
It give me error like "sh: 1: caffe: not found"
but when I use python, I can import caffe successfully.
could you tell me what's the problem?

**Comment by luoyetx** [comment]
put caffe's build/tools path to $PATH and use `which caffe` to checkout whether the system can locate caffe command.
