### ISSUE TITLE
ImportError: No module named common

### ISSUE THREAD

**Issue by ustcluq** [luoyetx/deep-landmark#31]

**Comment by luoyetx** [comment]
please run python code under project root directory.

**Comment by ustcluq** [comment]
I have run your code under the project root directory, but still has this mistake. 好伤悲

**Comment by luoyetx** [comment]
尝试下把 deep-landmark 的 root 目录 /path/to/deep-landmark 加入到 PYTHONPATH 里

```
$ export PYTHONPATH=/path/to/deep-landmark:$PYTHONPATH
```

**Comment by ustcluq** [comment]
问题解决啦。。多谢大神相助！！！！

在2017-04-01 09:15:02，Jie Zhangnotifications@github.com写道：

尝试下把 deep-landmark 的 root 目录 /path/to/deep-landmark 加入到 PYTHONPATH 里

$ export PYTHONPATH=/path/to/deep-landmark:$PYTHONPATH
