### ISSUE TITLE
[libprotobuf ERROR google/protobuf/text_format.cc:245]

### ISSUE THREAD

**Issue by ustcluq** [luoyetx/deep-landmark#32]
who can help me? Thanks!

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.SolverParameter: 25:9: Message type "caffe.SolverParameter" has no field named "log_file".
F0405 10:16:20.896741  2613 upgrade_proto.cpp:1101] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse SolverParameter file: prototxt/3_LE1_solver.prototxt
*** Check failure stack trace: ***
    @     0x7f597c55bdbd  google::LogMessage::Fail()
    @     0x7f597c55dc5d  google::LogMessage::SendToLog()
    @     0x7f597c55b9ac  google::LogMessage::Flush()
    @     0x7f597c55e57e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f597cc8f9be  caffe::ReadSolverParamsFromTextFileOrDie()
    @           0x407ce4  train()
    @           0x40590c  main
    @     0x7f597b569f45  (unknown)
    @           0x40617b  (unknown)
Aborted (core dumped)

**Comment by luoyetx** [comment]
I already remove `log_file` field in solver.prototxt long time ago. Why you still get this error ?

**Comment by ustcluq** [comment]
Sorry, I used the older version. Now it is OK. Thank you very much!
