### ISSUE TITLE
The test results of level2 and level3 are worse

### ISSUE THREAD

**Issue by ustcluq** [luoyetx/deep-landmark#33]
Test Number: 3466
Time Consume: 24.520 s
FPS: 141.351
LEVEL - 1
Mean Error:
    Left Eye       = 0.022420
    Right Eye      = 0.023296
    Nose           = 0.030268
    Left Mouth     = 0.028703
    Right Mouth    = 0.028891
Failure:
    Left Eye       = 0.060300
    Right Eye      = 0.064628
    Nose           = 0.137046
    Left Mouth     = 0.110502
    Right Mouth    = 0.122331
################## Summary #####################
Test Number: 3466
Time Consume: 46.793 s
FPS: 74.071
LEVEL - 2
Mean Error:
    Left Eye       = 0.090333
    Right Eye      = 0.015689
    Nose           = 0.018732
    Left Mouth     = 0.020073
    Right Mouth    = 0.091233
Failure:
    Left Eye       = 0.983266
    Right Eye      = 0.031448
    Nose           = 0.040969
    Left Mouth     = 0.055972
    Right Mouth    = 0.973745
################## Summary #####################
Test Number: 3466
Time Consume: 71.581 s
FPS: 48.421
LEVEL - 3
Mean Error:
    Left Eye       = 0.089275
    Right Eye      = 0.014808
    Nose           = 0.061951
    Left Mouth     = 0.063852
    Right Mouth    = 0.089410
Failure:
    Left Eye       = 0.980958
    Right Eye      = 0.031160
    Nose           = 0.804385
    Left Mouth     = 0.866128
    Right Mouth    = 0.970571

Where is my wrong, thanks!

**Comment by luoyetx** [comment]
@ustcluq Sorry for the late reply. It seems the Level-1 network is trained well, but some networks in Level-2 and Level-3 is not well. Please pay attention to the training loss of these networks, some weight initialization of these networks makes the training process failed (loss is not converge). You should re-train these networks.

**Comment by ustcluq** [comment]
Thank you~
